package cursor

import (
	"encoding/json"
	"os"
	"path/filepath"

	"github.com/OlegHQ/agentpack/internal/paths"
)

func writeManifests(root string) error {
	marketplace := map[string]any{"name": "agentpack", "owner": map[string]string{"name": "agentpack"}, "metadata": map[string]string{"description": "Pinned GitHub skills and Claude plugins from pack.lock", "version": "1.0.0"}, "plugins": []any{map[string]string{"name": paths.StagedAgentpackBundleName, "source": paths.StagedAgentpackBundleName, "description": "Merged pack.lock content staged by agentpack"}}}
	plugin := map[string]any{"name": paths.StagedAgentpackBundleName, "displayName": "agentpack bundle", "version": "1.0.0", "description": "Merged plugins and skills from pack.lock (agentpack).", "author": map[string]string{"name": "agentpack"}, "license": "MIT", "keywords": []string{"agentpack", "pack.lock"}}
	for path, value := range map[string]any{filepath.Join(root, ".cursor-plugin", "marketplace.json"): marketplace, filepath.Join(root, paths.StagedAgentpackBundleName, ".cursor-plugin", "plugin.json"): plugin} {
		if err := writeJSON(path, value); err != nil {
			return err
		}
	}
	return nil
}
func writeReadme(pack string) error {
	body := "# agentpack bundle\n\nThis directory is generated by **agentpack** from `pack.lock` under `$STAGING/cursor` when you run `sync`.\nIt mirrors the [Cursor plugin layout](https://cursor.com/docs/reference/plugins) (`plugin_spec.md` in the agentpack repo).\n\nDo not commit this tree — it is a local staging copy; `agentpack agent` points **`CURSOR_CONFIG_DIR`** at **`$STAGING/cursor`** and defaults **`--workspace`** to the canonical project root.\n"
	return os.WriteFile(filepath.Join(pack, "README.md"), []byte(body), 0o644)
}
func writeJSON(path string, value any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
