//! Write Cursor plugin manifests (`marketplace.json`, `plugin.json`) and README.

use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::error::{AgentpackError, Result};
use crate::fs_util::{write_json_value, write_text_file};
use crate::paths::STAGED_AGENTPACK_BUNDLE_NAME;

/// Writes **`$STAGING/cursor/.cursor-plugin/marketplace.json`** and
/// **`$STAGING/cursor/<bundle>/.cursor-plugin/plugin.json`** per Cursor multi-plugin layout.
pub(in crate::staging) fn write_cursor_pack_plugin_manifests(cursor_root: &Path) -> Result<()> {
    let marketplace_dir = cursor_root.join(".cursor-plugin");
    fs::create_dir_all(&marketplace_dir).map_err(|e| AgentpackError::io(&marketplace_dir, e))?;

    let pack_plugin = cursor_root.join(STAGED_AGENTPACK_BUNDLE_NAME);
    let plugin_manifest_dir = pack_plugin.join(".cursor-plugin");
    fs::create_dir_all(&plugin_manifest_dir)
        .map_err(|e| AgentpackError::io(&plugin_manifest_dir, e))?;

    let marketplace: Value = serde_json::json!({
        "name": "agentpack",
        "owner": { "name": "agentpack" },
        "metadata": {
            "description": "Pinned GitHub skills and Claude plugins from pack.lock",
            "version": "1.0.0"
        },
        "plugins": [{
            "name": STAGED_AGENTPACK_BUNDLE_NAME,
            "source": STAGED_AGENTPACK_BUNDLE_NAME,
            "description": "Merged pack.lock content staged by agentpack"
        }]
    });
    write_json_value(&marketplace_dir.join("marketplace.json"), &marketplace)?;

    let plugin_json: Value = serde_json::json!({
        "name": STAGED_AGENTPACK_BUNDLE_NAME,
        "displayName": "agentpack bundle",
        "version": "1.0.0",
        "description": "Merged plugins and skills from pack.lock (agentpack).",
        "author": { "name": "agentpack" },
        "license": "MIT",
        "keywords": ["agentpack", "pack.lock"]
    });
    write_json_value(&plugin_manifest_dir.join("plugin.json"), &plugin_json)?;
    Ok(())
}

pub(in crate::staging) fn write_cursor_pack_plugin_readme(pack_plugin: &Path) -> Result<()> {
    let readme = pack_plugin.join("README.md");
    let body = r#"# agentpack bundle

This directory is generated by **agentpack** from `pack.lock` under `$STAGING/cursor` when you run `sync`.
It mirrors the [Cursor plugin layout](https://cursor.com/docs/reference/plugins) (`plugin_spec.md` in the agentpack repo).

Do not commit this tree — it is a local staging copy; `agentpack agent` points **`CURSOR_CONFIG_DIR`** at **`$STAGING/cursor`** and defaults **`--workspace`** to the canonical project root.
"#;
    write_text_file(&readme, body)
}
